### ISSUE TITLE
Missing Customer details in Chat.io chat reopened from archives

### ISSUE THREAD

**Issue by QAjetan** [livechat/platform-api-support#2]
Requirements: 
-Chat in Archives

Repro Steps:
-Open Archives
-Search chat with "Contact info" + "Technology"
-Click "Open it again"

Expected Results: 
Chat should open and assigned to you with "Contact info" and "Technology" information

Actual Results: 
Chat appears, assigned to you but without "Contact info" and "Technology" information

<img width="1675" alt="open it again" src="https://user-images.githubusercontent.com/25999766/33434867-e28a9788-d5e0-11e7-9e57-93bb3015fc19.png">

<img width="1680" alt="archives" src="https://user-images.githubusercontent.com/25999766/33434868-e2a3d9a0-d5e0-11e7-88e2-9bbbde3b988b.png">

**Comment by gluszczyk** [comment]
bug? what bug, go away! **solved**
