### ISSUE TITLE
[Agent API][multicast] Agents do not receive push notification in case the request contains group

### ISSUE THREAD

**Issue by marcindebski** [livechat/platform-api-support#4]
Agent API version: 0.4
transport: websocket
method: multicast

Agent does not receive push notification when request contains group that agent belongs to. Agent should have received push notification, even though status is set to 'not_accepting_chats'.

Steps to reproduce:
1. Add agent to group.
2. Using Agent API (version 0.4), send multicast to group that agent belongs to. For instance:
{"action": "multicast", "request_id": "9095686376", "payload": {"scopes": {"agents": {"groups": [3]}}, "content": {"example": {"nested": "broadcastcontent"}}}}
3. Check if push notification was delivered to agent.

Expected Results:
Push notification should be delivered to agent.

Actual Results:
Agent does not receive push notification.

**Comment by gluszczyk** [comment]
fixed
